-- ============================================
-- PPC: Delay No More — Supabase Schema
--
-- Run this in Supabase SQL Editor:
-- Dashboard → SQL Editor → New Query → Paste → Run
-- ============================================

-- 1. Trips table
CREATE TABLE IF NOT EXISTS trips (
  id varchar primary key,
  name text not null,
  start_date text not null,
  end_date text not null,
  pin varchar(6) not null unique,
  destination_airport text,
  return_airport text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

CREATE INDEX IF NOT EXISTS idx_trips_pin ON trips (pin);

-- 2. Participants table
CREATE TABLE IF NOT EXISTS participants (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    color INTEGER DEFAULT 0,
    home_airport TEXT,
    destination_airport TEXT,
    joined_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(trip_id, name)
);

CREATE INDEX IF NOT EXISTS idx_participants_trip ON participants (trip_id);

-- 3. Flights table
CREATE TABLE IF NOT EXISTS flights (
    id TEXT PRIMARY KEY,
    trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    flight_number TEXT NOT NULL,
    airline TEXT DEFAULT '',
    departure JSONB DEFAULT '{}',
    arrival JSONB DEFAULT '{}',
    date TEXT DEFAULT '',
    duration TEXT DEFAULT '',
    status TEXT DEFAULT 'scheduled',
    aircraft TEXT DEFAULT '',
    gate TEXT DEFAULT '',
    added_by TEXT DEFAULT '',
    added_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_flights_trip ON flights (trip_id);

-- 4. Notes table
CREATE TABLE IF NOT EXISTS notes (
    id TEXT PRIMARY KEY,
    trip_id TEXT NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_notes_trip ON notes (trip_id);

-- ============================================
-- Row Level Security (RLS)
--
-- Using anon key with open policies since
-- auth is PIN-based, not user-account-based.
-- ============================================

ALTER TABLE trips ENABLE ROW LEVEL SECURITY;
ALTER TABLE participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE flights ENABLE ROW LEVEL SECURITY;
ALTER TABLE notes ENABLE ROW LEVEL SECURITY;

-- IMPORTANT: The custom JWT generated by the Edge Function contains a `trip_id` claim.
-- We cast it to TEXT for comparison.

-- TRIPS:
-- 1. Anyone can create a new trip (no JWT needed yet)
CREATE POLICY "Allow insert trip" ON trips FOR INSERT WITH CHECK (true);
-- 2. You can only read/update a trip if the JWT trip_id matches the row id
CREATE POLICY "Allow select/update trip if JWT matches" ON trips FOR SELECT USING (id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow update trip if JWT matches" ON trips FOR UPDATE USING (id = (auth.jwt() ->> 'trip_id'));

-- PARTICIPANTS:
CREATE POLICY "Allow insert participant if JWT matches" ON participants FOR INSERT WITH CHECK (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow select participant if JWT matches" ON participants FOR SELECT USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow update participant if JWT matches" ON participants FOR UPDATE USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow delete participant if JWT matches" ON participants FOR DELETE USING (trip_id = (auth.jwt() ->> 'trip_id'));

-- FLIGHTS:
CREATE POLICY "Allow insert flight if JWT matches" ON flights FOR INSERT WITH CHECK (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow select flight if JWT matches" ON flights FOR SELECT USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow update flight if JWT matches" ON flights FOR UPDATE USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow delete flight if JWT matches" ON flights FOR DELETE USING (trip_id = (auth.jwt() ->> 'trip_id'));

-- NOTES:
CREATE POLICY "Allow insert note if JWT matches" ON notes FOR INSERT WITH CHECK (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow select note if JWT matches" ON notes FOR SELECT USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow update note if JWT matches" ON notes FOR UPDATE USING (trip_id = (auth.jwt() ->> 'trip_id'));
CREATE POLICY "Allow delete note if JWT matches" ON notes FOR DELETE USING (trip_id = (auth.jwt() ->> 'trip_id'));
